map:
  zoom_factor: 1.5
node:
  triangle_base_size: 0.3
  del_pen: "#FF0000"
  del_pen_w: 2
  del_brush: "#FF6464"
  mov_pen: "#FF0000"
  mov_pen_w: 2
  mov_brush: "#FF6464"
move:
  click_threshold: 10
window:
  pos_x: 100
  pos_y: 100
  width: 1200
  height: 800
