main_window:
  pos_x: 100
  pos_y: 100
  width: 1200
  height: 800
map_widget:
  zoom_factor: 1.5
map_graphics_view:
  move_mode:
    click_th: 10
  node:
    triangle_base_size: 0.3
    del_pen: "#FF0000"
    del_pen_w: 2
    del_brush: "#FF6464"
    mov_pen: "#FF0000"
    mov_pen_w: 2
    mov_brush: "#FF6464"
